language: cpp

sudo: false

compiler:
  - gcc
  - clang

env:
  global:
    - GODOT_TAG=master # I like to living dangerously...
    # Cannot use release given travis's glibc clash with -ffast-math with clang
    # other solution is to set `-D__extern_always_inline="extern __always_inline"`
    - EXTRA_OPTS="-j4 target=debug tools=no module_pythonscript_enabled=yes"
  matrix:
    - GODOT_TARGET=x11
    # nothing else yet...

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - scons
      - pkg-config
      - libx11-dev
      - libxcursor-dev
      - libasound2-dev
      - libfreetype6-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - libssl-dev
      - libxinerama-dev
      - libxrandr-dev
      # Need gcc > 4.6 for -std=c++11
      - gcc-4.8
      - g++-4.8

before_script:
  - git clone -b $GODOT_TAG --single-branch  --recursive --depth 1 https://github.com/godotengine/godot.git
  - ln -s `pwd`/pythonscript godot/modules/pythonscript

script:
  - if [[ "$CXX" == "g++" ]]; then make compile OPTS="platform=$GODOT_TARGET $EXTRA_OPTS CXX=g++-4.8 CC=gcc-4.8"; fi
  - if [[ "$CXX" == "clang++" ]]; then make compile OPTS="platform=$GODOT_TARGET $EXTRA_OPTS use_llvm=yes"; fi
