language: cpp

sudo: false

compiler:
  - gcc
  - clang

env:
  global:
    - GODOT_TAG=master # I like to living dangerously...
    - EXTRA_OPTS="-j4 openssl=builtin target=release module_pythonscript_enabled=yes"
  matrix:
    - GODOT_TARGET=x11
    # nothing else yet...

addons:
  apt:
    packages:
      - build-essential
      - scons
      - pkg-config
      - libx11-dev
      - libxcursor-dev
      - libasound2-dev
      - libfreetype6-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - libssl-dev
      - libxinerama-dev
      - libxrandr-dev

before_script:
  - git clone -b $GODOT_TAG --single-branch  --recursive --depth 1 https://github.com/godotengine/godot.git
  - ln -s `pwd`/pythonscript godot/modules/pythonscript
  # See issue travis-ci/travis-ci#1379
  - [ "$CXX" = "g++" ] && sudo apt-get install -qq g++-4.8
  - [ "$CXX" = "g++" ] && export CXX="g++-4.8" CC="gcc-4.8"

script:
  - [ "$CXX" = "g++" ] && make compile EXTRA_OPTS="$EXTRA_OPTS" OPTS="platform=$GODOT_TARGET use_llvm=no"
  - [ "$CXX" = "clang++" ] && make compile EXTRA_OPTS="$EXTRA_OPTS" OPTS="platform=$GODOT_TARGET use_llvm=yes"
