image: Visual Studio 2017

# Skip build on normal pushes
# skip_non_tags: true
# artifacts:
#   - path: godot\bin\*.exe
#     name: GodotBinary
#   - path: godot\bin\*gdnative_wrapper_code*.lib
#     name: GodotGDNativeWrapper

environment:
  VS: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat
  CPP: clang.exe -E
  PYTHON: C:\Python36-x64
  matrix:
    - TARGET_PLATFORM: windows-64
      ARCH: amd64
      TARGET_BACKEND: cpython

install:
  - set "PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - pip install --egg scons  # it will fail on AppVeyor without --egg flag
  # - if defined VS call "%VS%" %ARCH%  # if defined - so we can also use mingw

before_build:
  - git rev-parse HEAD
  - python --version
  - scons --version
  - clang.exe --version
  # - cl.exe

build_script:
  - scons LINK=clang.exe CC=clang.exe platform=%TARGET_PLATFORM% backend=%TARGET_BACKEND% PYTHON=python --tree=all gdnative_parse_cpp="%CPP%"

# deploy:
#   description: 'Godot binaries deployed by Travis CI and AppVeyor'
#   provider: GitHub
#   auth_token:
#     secure: DYTTAkQFPIDq2YL6hPMOttlHdJ9ZL6dYdOtGFIEneO8BTYx6keJRvewsdzgP2QGA
#   artifact: GodotBinary, GodotGDNativeWrapper
#   on:
#     appveyor_repo_tag: true
