image: Visual Studio 2015

# Skip build on normal pushes
# skip_non_tags: true
# artifacts:
#   - path: godot\bin\*.exe
#     name: GodotBinary
#   - path: godot\bin\*gdnative_wrapper_code*.lib
#     name: GodotGDNativeWrapper

environment:
  VS: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat
  CPP: gcc.exe -E
  PYTHON: C:\Python36-x64
  matrix:
    - TARGET_PLATFORM: windows-64
      ARCH: amd64
      TARGET_BACKEND: cpython

install:
  - set "PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - set "PATH=C:\\mingw-w64\\x86_64-6.3.0-posix-seh-rt_v5-rev1\\mingw64\\bin;%PATH%"
  - pip install --egg scons  # it will fail on AppVeyor without --egg flag
  # Cannot use msvc due to Python source code embedding in to
  # `pythonscriptcffi.gen.c` as a string bigger than 65k bytes...
  # - if defined VS call "%VS%" %ARCH%  # if defined - so we can also use mingw

before_build:
  - git rev-parse HEAD
  - python --version
  - scons --version
  - gcc --version

build_script:
  - scons platform=%TARGET_PLATFORM% backend=%TARGET_BACKEND% PYTHON=python gdnative_parse_cpp="%CPP%" && exit 0
  - appveyor PushArtifact build\windows-64-cpython\pythonscript.dll
  - appveyor PushArtifact pythonscript\pythonscript.o
  - appveyor PushArtifact pythonscript\cffi_bindings\pythonscriptcffi.gen.o
  - appveyor PushArtifact build\windows-64-cpython\python36.lib
  - appveyor PushArtifact platforms\gdnative\gdnative_wrapper_code.windows.opt.64.lib

# deploy:
#   description: 'Godot binaries deployed by Travis CI and AppVeyor'
#   provider: GitHub
#   auth_token:
#     secure: DYTTAkQFPIDq2YL6hPMOttlHdJ9ZL6dYdOtGFIEneO8BTYx6keJRvewsdzgP2QGA
#   artifact: GodotBinary, GodotGDNativeWrapper
#   on:
#     appveyor_repo_tag: true
